name: Lab 58 - Cache Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  baseline:
    name: Baseline (no cache)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (baseline)
        run: npm ci

      - name: Build (baseline)
        run: npm run build --if-present
