
name: Lab 58 - Cache Demo

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  setup-node-cache:
    name: Built-in caching via setup-node (recommended)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Smoke test
        run: npm test

  manual-cache:
    name: Manual caching with actions/cache (advanced)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache npm cache dir
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node20-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-node20-
            npm-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Smoke test
        run: npm test
