name: Lab 58 - Cache Demo

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  setup-node-cache:
    name: Built-in caching via setup-node (recommended)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Smoke test
        run: npm test
