name: Lab 58 - Cache Demo

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  cached-setup-node:
    name: Cached via setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node with built-in cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies (cached)
        run: npm install

      - name: Build (cached)
        run: npm run build --if-present

